---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helmbasic-develop
  namespace: develop
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:v*
spec:
  releaseName: helmbasic-develop
  chart:
    git: git@github.com:shantanuyelwande/helmflux
    path: helmbasics
    ref: develop
  values:
    environment: development
    replicaCount: 1
    image:
      repository: shantanuy/bitnami-apache
      tag: v0.0.1    
    ingress:
      host: mywebserver.dev.kubesandclouds.com
